env: "local" # local - текстовые логи, prod - JSON логи
host: "0.0.0.0:8080" # Порт для входящих запросов

backends:
  - url: "http://backend1:80"
  - url: "http://backend2:80"
  - url: "http://backend3:80"

rate_limiter:
  default_bucket_capacity: 30
  default_refill: 1
  default_refill_interval: 2s
  bucket_settings_database:
    host: "postgres"
    port: "5432"
    user: "postgres"
    database: "postgres"
    password: "postgres"
  api:
    host: "0.0.0.0:9090"